### ISSUE TITLE
Watchlisted rule returns null value

### ISSUE THREAD

**Issue by sameleff** [Maintainerr/Maintainerr#1203]
**Describe the bug**
Watchlisted rule returns null value for TV Shows that are included in a user's watchlist.

**To Reproduce**
1. Add a TV Show to a particular Plex user's watchlist.
2. Create a new rule that excludes TV Shows that are on the user's watchlist.
3. Run the rule.
4. TV Show is included in the "Leaving Soon" collection.

**Expected behavior**
Using "Plex - [list] Watchlisted by (username) [experimental]" rule, expect it to return a list of all users that have watchlisted a particular TV Show.
Instead, it returns a null value `[]`.

**Screenshots**
Screenshots for rule creation:
![image](https://github.com/user-attachments/assets/857626cc-8da8-476c-a1bf-af1b7930af12)
![image](https://github.com/user-attachments/assets/0712f7d6-5798-4dee-860b-c5985ce9db6f)
![image](https://github.com/user-attachments/assets/32dabe86-9bd7-4eee-97d5-e30eaf9d90c0)
![image](https://github.com/user-attachments/assets/8bf69432-6a57-41e1-8959-0575b817b4be)

Output from Test Media using Breaking Bad as an example. Confirmed it is included in the Plex watchlist.
```
- plexId: 63158
  result: true
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Plex - [list] Collections media is present in (titles)
          firstValue:
            - TV Shows Leaving Soon
            - IMDb Top 250
            - IMDb Popular
          secondValueName: text
          secondValue: TV Show Vault
          result: true
        - operator: AND
          action: contains_partial
          firstValueName: Plex - [list] Users that saw all available episodes
          firstValue: []
          secondValueName: text
          secondValue: sameleff
          result: false
    - id: 1
      result: false
      operator: OR
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Plex - [list] Collections media is present in (titles)
          firstValue:
            - TV Shows Leaving Soon
            - IMDb Top 250
            - IMDb Popular
          secondValueName: text
          secondValue: TV Show Vault
          result: true
        - operator: AND
          action: before
          firstValueName: Plex - Date added
          firstValue: 2023-10-05T22:39:42.000Z
          secondValueName: custom_days
          secondValue: 2024-02-12T18:26:36.932Z
          result: true
        - operator: AND
          action: equals
          firstValueName: Plex - Total views
          firstValue: 0
          secondValueName: number
          secondValue: 0
          result: true
        - operator: AND
          action: not_contains_partial
          firstValueName: Plex - [list] Watchlisted by (username) [experimental]
          firstValue: []
          secondValueName: text
          secondValue: sameleff
          result: true
```

**Device (please complete the following information):**
 - OS: Unraid 6.12.8
 - Docker compose using `ghcr.io/jorenn92/maintainerr:main` image

**Additional context**
The user involved is a non-admin on the Plex server.
