### ISSUE TITLE
Items get repeatedly removed and added back to collections

### ISSUE THREAD

**Issue by Zipties** [Maintainerr/Maintainerr#1446]
I am having an issue where all items in the collection are being removed each night, and then being added again shortly after

![image](https://github.com/user-attachments/assets/091fa261-ec97-411b-bb3c-ed1c94a993d9)

All my rules are exhibiting this behavior and I am pretty stumped over it. Here is one of them

 ```mediaType: MOVIES
rules:
  - "0":
      - firstValue: Plex.seenBy
        action: CONTAINS
        lastValue: Overseerr.addUser
      - operator: AND
        firstValue: Overseerr.isRequested
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Overseerr.mediaAddedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "90"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
  - "1":
      - operator: OR
        firstValue: Overseerr.mediaAddedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "60"
      - operator: AND
        firstValue: Overseerr.isRequested
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
  - "2":
      - operator: OR
        firstValue: Plex.lastViewedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "365"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
  - "3":
      - operator: OR
        firstValue: Plex.viewCount
        action: EQUALS
        customValue:
          type: number
          value: 0
      - operator: AND
        firstValue: Plex.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "730"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
```

**Comment by benscobie** [comment]
Could you enable debug logging:  https://docs.maintainerr.info/Installation.html#enabling-debug-logging

Wait for this to happen a few more times and then attach the logs here.

I'd also suggest using Test Media on one of those seasons a few times per day, save the results and then compare and/or attach here.

**Comment by Zipties** [comment]
Been busy with holiday plans but didn't want to leave this stale. I grabbed the debug logs but haven't looked at them yet, it is still happening though. 
[maintainerr-2024-12-23.log](https://github.com/user-attachments/files/18235092/maintainerr-2024-12-23.log)

**Comment by ydkmlt84** [comment]
> Been busy with holiday plans but didn't want to leave this stale. I grabbed the debug logs but haven't looked at them yet, it is still happening though. [maintainerr-2024-12-23.log](https://github.com/user-attachments/files/18235092/maintainerr-2024-12-23.log)

It looks like you may have a mixture of things happening. I could be wrong. You are having A LOT of TMDB/TVDB id errors. Maintainerr uses these IDs to talk with *arr services to make sure we are talking about the exact same movie. These IDs come from your Plex metadata. 

When Maintainerr tries to remove the items, it can't tell the other services to do something with them, because those services are saying "that item doesn't exist". It technically does but not with the information that Maintainerr is sending it, that it got from Plex. see #1469 for another discussion on the topic.

The other thing I wanted to ask about is if you are using Smart Collections, with Custom Collections in Maintainerr? 
I see this in your logs:
```
[maintainerr]  |  23/12/2024 08:10:47  [WARN] [PlexApiService] Couldn't find collection with id 385545
[maintainerr]  |  23/12/2024 08:10:47  [DEBUG] [PlexApiService] Plex Server didnt respond with a valid 2xx status code, response code: 404
[maintainerr]  |  23/12/2024 08:10:47  [WARN] [CollectionsService] An error occurred while searching for a specific Plex collection.
[maintainerr]  |  23/12/2024 08:10:47  [DEBUG] [CollectionsService] Cannot read properties of undefined (reading 'smart')
```

I believe that cleaning up your metadata, in Plex, is going to solve a lot of your problems, and at the very least it is going to clean up your Maintainerr logs.

https://support.plex.tv/articles/201018497-fix-match-match/

**Comment by Zipties** [comment]
I am starting to feel this is probably some kind of conflict with kometa. Does it seem plausible it could be doing something to cause the tvdb and metadata errors?

> The other thing I wanted to ask about is if you are using Smart Collections, with Custom Collections in Maintainerr?
I see this in your logs:

I jsut have maintainarr set to create its own collections, I am not trying to do anything fancy. Kometa makes numerous collections smart and otherwise though. I made sure kometa is set not to delete unknown collections and confirmed it wasn't deleting maintainarrs.

**Comment by ydkmlt84** [comment]
I use Kometa but almost exclusively for overlays and a few collections. Maybe try to make a rule that would match a small section of your library, and see if ensuring the metadata for those specific items, makes any kind of difference.

**Comment by Zipties** [comment]
I disabled Kometa, and did a fresh metadata cleanup and still see the flood of API errors in the logs you pointed out. 

```[maintainerr]  |  01/01/2025 16:00:07  [DEBUG] [RadarrGetterService] Couldn't fetch Radarr metadate for media 'Till Death' with id '7418'. As a result, no Radarr query could be made.
[maintainerr]  |  01/01/2025 16:00:07  [WARN] [RadarrApi] Could not find Movie with TMDb id 280 in Radarr
[maintainerr]  |  01/01/2025 16:00:07  [DEBUG] [RadarrGetterService] Couldn't fetch Radarr metadate for media 'Terminator 2: Judgment Day' with id '235900'. As a result, no Radarr query could be made.```

These seem to be because I have another radarr instance for 4k movies. I added the 4k server, but im not sure how I'd include both servers in the rule. 

I think that may be a redherring though, as  I don't see sonarr errors in the logs, and TV shows have the same issue. I only have a single sonarr instance. I spot checked a half a fozen like the below which do exist in sonarr, and do not have errors in the logs

![CleanShot 2025-01-01 at 21 41 00](https://github.com/user-attachments/assets/827a1040-c3f6-4b03-90f7-201ee711d9f6)
I don't see anything in the logs referencing the show, so I assume it's under an id. 

```- plexId: 237511
  result: true
  sectionResults:
    - id: 0
      result: true
      ruleResults:
        - operator: OR
          action: contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - latesttvshows
            - lists
          secondValueName: text
          secondValue: lists
          result: true
        - operator: AND
          action: equals
          firstValueName: Plex - Total views
          firstValue: 0
          secondValueName: number
          secondValue: 0
          result: true
        - operator: AND
          action: before
          firstValueName: Sonarr - Date added
          firstValue: 2024-11-05T03:57:06.000Z
          secondValueName: custom_days
          secondValue: 2024-12-19T03:43:18.215Z
          result: true
```

**Comment by mlamoure** [comment]
I experience this exact issue as well, and have for some time.  I also use Kometa regularly, make use of collections heavily, and have a decent sized Movie library (~1200+ movies).  TV Shows do not experience this problem for me.  

I also use the Plex Meta Cleanup (now called ImageMaid) on a weekly basis to keep my database clean as I’ve had issues in the past, but this routine seems to keep my database clean as I haven’t had any plex issues in over a year.

I do not have a separate Radarr instance for 4k, just single.

Happy to also test or provide logs.  I’d love to get this solved.

**Comment by appiekap653** [comment]
I have the same and had it for quite some time now, before I had Kometa and ImageMaid and after.

I also have brought up the issue before in issue #1140.

[My comment on the issue](https://github.com/jorenn92/Maintainerr/issues/1140#issuecomment-2345498605)

You get a lot of log messages in Maintainerr like these:

`removed *movie/show*` and `added *movie/show`

But what you don't see are the usual `successfully handled *movie/show*`

If you look at the logs of Sonarr and Radarr at the times of those 'removed' messages from Maintainerr, there are no api calls to remove/delete/unmonitor the particular media.

**Comment by Zipties** [comment]
Just checking back in on this to see if anyone has any ideas. All my TV shows have the below behavior. I don't see any IMDB errors being reported, and my media is tagged with the correct IDs. Movies has the same rules but doesn't appear to have the issue although it's a much smaller dataset

```
- plexId: 237638
  result: true
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - appletv
            - lists
          secondValueName: text
          secondValue: lists
          result: true
        - operator: AND
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - appletv
            - lists
          secondValueName: text
          secondValue: dnd
          result: true
        - operator: AND
          action: before
          firstValueName: Plex - Last view date
          firstValue: null
          secondValueName: custom_days
          secondValue: 7776000
          result: false
    - id: 1
      result: true
      operator: OR
      ruleResults:
        - operator: OR
          action: equals
          firstValueName: Plex - Total views
          firstValue: 0
          secondValueName: number
          secondValue: 0
          result: true
        - operator: AND
          action: contains
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - appletv
            - lists
          secondValueName: text
          secondValue: lists
          result: true
        - operator: AND
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue:
            - appletv
            - lists
          secondValueName: text
          secondValue: dnd
          result: true
```

![Image](https://github.com/user-attachments/assets/0d5a2ae6-5b99-4519-9181-99f816b09451)

![Image](https://github.com/user-attachments/assets/9c20992f-ae3b-4263-8af8-896218a8452d)

**Comment by mlamoure** [comment]
It's interesting that you experience it on TV shows.  I experience the problem of coming on and off the Maintainerr lists on Movies only.  I have Kometa applied to both.

**Comment by benscobie** [comment]
@mlamoure @Zipties Could you [enable debug logging](https://docs.maintainerr.info/Installation/#enabling-debug-logging_1), wait for an add & remove cycle and then share your logs please.

**Comment by Zipties** [comment]
> [@mlamoure](https://github.com/mlamoure) [@Zipties](https://github.com/Zipties) Could you [enable debug logging](https://docs.maintainerr.info/Installation/#enabling-debug-logging_1), wait for an add & remove cycle and then share your logs please.

[maintainerr-2025-02-28.log](https://github.com/user-attachments/files/19031056/maintainerr-2025-02-28.log)

Sorry, I had them enabled but forgot to upload

**Comment by Zipties** [comment]
Here is the 25th which shows adds

[maintainerr-2025-02-25.log](https://github.com/user-attachments/files/19031139/maintainerr-2025-02-25.log)

here is yesterday's which shows removals 

[maintainerr-2025-02-27.log](https://github.com/user-attachments/files/19031125/maintainerr-2025-02-27.log)

**Comment by benscobie** [comment]
I think what we'll need to do is include the rule results with the added & removed logs. Then we should be able to identify which rule(s) are being problematic and go from there.

**Comment by Zipties** [comment]
> I think what we'll need to do is include the rule results with the added & removed logs. Then we should be able to identify which rule(s) are being problematic and go from there.
> 
> You have a ton of `seasons is not iterable errors` though, but they're in both logs so likely unrelated.

Is there a way to do this programmatically? I keep trying to catch a rule flipping before a run and have never witnessed it.

**Comment by Zipties** [comment]
@benscobie running it now, so far the manual rule runs haven't reproduced the issue so I'll give it a day or two.

PS, nice work on the new progress bar

**Comment by Zipties** [comment]
Alrighty, I have something to report. 

![Image](https://github.com/user-attachments/assets/2d8e9301-096b-4a5a-b2fc-6a601cc187c6)

All remvoes show up as 'manual' and aren't clickable. 

the added meta looks like

```plexId: 554934
result: true
sectionResults:
  - id: 0
    result: false
    ruleResults:
      - operator: OR
        action: contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: lists
        result: true
      - operator: AND
        action: not_contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: dnd
        result: true
      - operator: AND
        action: before
        firstValueName: Tautulli - Last view date
        firstValue: null
        secondValueName: custom_days
        secondValue: 7776000
        result: false
    operator: OR
  - id: 1
    result: true
    operator: OR
    ruleResults:
      - operator: OR
        action: equals
        firstValueName: Tautulli - Times viewed
        firstValue: 0
        secondValueName: number
        secondValue: 0
        result: true
      - operator: AND
        action: contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: lists
        result: true
      - operator: AND
        action: not_contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: dnd
        result: true
```

However, this seems to be the only collection doing it anymore so it could be an issue with that rule set.

**Comment by benscobie** [comment]
Interesting 🤔 Could you provide your logs for that time period?

**Comment by Zipties** [comment]
[maintainerr-2025-04-18.log](https://github.com/user-attachments/files/19815385/maintainerr-2025-04-18.log)

[maintainerr-2025-04-17.log.gz](https://github.com/user-attachments/files/19815387/maintainerr-2025-04-17.log.gz)

here ya go

**Comment by benscobie** [comment]
> [maintainerr-2025-04-18.log](https://github.com/user-attachments/files/19815385/maintainerr-2025-04-18.log)
> 
> [maintainerr-2025-04-17.log.gz](https://github.com/user-attachments/files/19815387/maintainerr-2025-04-17.log.gz)
> 
> here ya go

The server appears to be restarting randomly, are there any errors in the containers logs? Full app crashes don't log to the .log files.

Did your added meta not include a `plexId:` line?

**Comment by Zipties** [comment]
I copied the full meta report, so I guess I the plex id wasn’t included 

I’m traveling for the holiday, but I was able to grab the complete console logs. I can’t really parse them properly on my phone though 

(It wouldn’t upload for whatever reason)
https://files.simpson.sh/seafhttp/f/471bea7066c24acfb471/?op=view

**Comment by benscobie** [comment]
> I copied the full meta report, so I guess I the plex id wasn’t included
> 
> I’m traveling for the holiday, but I was able to grab the complete console logs. I can’t really parse them properly on my phone though
> 
> (It wouldn’t upload for whatever reason) https://files.simpson.sh/seafhttp/f/471bea7066c24acfb471/?op=view

Hmm that is strange as well. I have pushed an update that should log any crashes to the log file, as those logs are only showing the current process.

I'm still trying to think about how (manual) could occur... the update I pushed also fixes some potential race conditions that could cause weird things to happen like this, but it's a stretch.

**Comment by Zipties** [comment]
I'm back home and took another look, and I must have omitted the Plex id as it is showing up on all the meta reports I've spot checked. 
`I have pushed an update that should log any crashes to the log file, as those logs are only showing the current process.`
Which tag is it I should target for the new build?

```
plexId: 554934
result: true
sectionResults:
  - id: 0
    result: false
    ruleResults:
      - operator: OR
        action: contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: lists
        result: true
      - operator: AND
        action: not_contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: dnd
        result: true
      - operator: AND
        action: before
        firstValueName: Tautulli - Last view date
        firstValue: null
        secondValueName: custom_days
        secondValue: 7776000
        result: false
    operator: OR
  - id: 1
    result: true
    operator: OR
    ruleResults:
      - operator: OR
        action: equals
        firstValueName: Tautulli - Times viewed
        firstValue: 0
        secondValueName: number
        secondValue: 0
        result: true
      - operator: AND
        action: contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: lists
        result: true
      - operator: AND
        action: not_contains_partial
        firstValueName: Radarr - [list] Tags
        firstValue:
          - kometa
          - lists
        secondValueName: text
        secondValue: dnd
        result: true
```

All removes are still shown as manual, and are affecting all collections again

**Comment by benscobie** [comment]
@Zipties same tag, you just need to pull the latest image down and restart the container.

**Comment by Zipties** [comment]
@benscobie removals have meta data attached now. Everything has been a legit removal so far so not much to share

**Comment by Zipties** [comment]
@benscobie most of the funky looking removals are still showing manual. I am also seeing some removals that the meta shows that the reason is because it couldn't contact tautulli. That's possible, but I havent observed any issues with it or in the logs. 

[maintainerr-2025-04-22.log.gz](https://github.com/user-attachments/files/19874766/maintainerr-2025-04-22.log.gz)
[maintainerr-2025-04-23.log](https://github.com/user-attachments/files/19874767/maintainerr-2025-04-23.log)

**Comment by rjwinks** [comment]
@benscobie I'm also experiencing the (manual) removals on my Movies collection.

**Comment by Zipties** [comment]
I setup a test rule that added all media with a certain tag in radarr, and set it to delete everything in 100 days. The rule is working properly, and has counted down 20 days on every media item

So, it seems to be an issue with the last viewed date conditions I have (see earlier posts) setup on the other rules

**Comment by rjwinks** [comment]
@Zipties I'm in the same boat. Like how simple can I make this rule to stop this behavior lol.

I feel like the only reliable services I can base rules off of are radarr and sonarr at this point.

**Comment by benscobie** [comment]
Just getting around to looking at this again, have just returned from vacation.

It is strange that they would show manual in that case, as if the change was the result of a rule then meta should show instead, but here we are 😆. I'll need to add some additional logging around the manual process to try and pinpoint what is going wrong.

**Comment by rjwinks** [comment]
[maintainerr-2025-05-07.log.gz](https://github.com/user-attachments/files/20174823/maintainerr-2025-05-07.log.gz)
[maintainerr-2025-05-11.log.gz](https://github.com/user-attachments/files/20174822/maintainerr-2025-05-11.log.gz)

Hi @benscobie 

Attached my logs from the most recent days where my movie collection removed all and re-added (5/7/25) I was on 2.14.0 at that time. I've switched back to pr-1705 and on 5/11/25 my TV collection did the remove/re-add again.

The (meta) for the TV removals are all blank.

I've simplified my rules down as much as I can:

TV:

mediaType: SHOWS
rules:
  - "0":
      - operator: AND
        firstValue: Sonarr.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "60"
  - "1":
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: 1 - rjwinks
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: keep
  - "2":
      - operator: AND
        firstValue: Sonarr.unaired_episodes
        action: EQUALS
        customValue:
          type: boolean
          value: "false"

Movies:

mediaType: MOVIES
rules:
  - "0":
      - operator: OR
        firstValue: Radarr.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "60"
  - "1":
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: 1 - rjwinks
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: keep
  - "2":
      - operator: AND
        firstValue: Radarr.fileQuality
        action: EQUALS
        customValue:
          type: number
          value: 1080

**Comment by rjwinks** [comment]
Hi @benscobie not sure if you want more logs, the TV show collection did it again a few more times on 2025-05-13 so I can reupload the full log again if needed.

**Comment by benscobie** [comment]
Your logs are littered with Plex fetch failures which certainly won't be helping the situation. That might be fixed in the future when we add retries for failed Plex requests. In the mean time I would check your [Plex server logs](https://support.plex.tv/articles/200250417-plex-media-server-log-files/) to see if there's anything obviously wrong in there.

**Comment by rjwinks** [comment]
Hmm ok I’ll take a look at my Plex logs. 

I’m curious why adding/removing from collections where my rules don’t use Plex as an input would be impacted? I can imagine when it comes time to remove the media but before that point I’m surprised a plex connection error factors in.

**Comment by benscobie** [comment]
> I’m curious why adding/removing from collections where my rules don’t use Plex as an input would be impacted? I can imagine when it comes time to remove the media but before that point I’m surprised a plex connection error factors in.

Metadata is fetched from Plex in various other places. E.g. for Sonarr rules we need to fetch show metadata when targeting seasons/episodes so that we can get the TVDB ID to look that up in Sonarr.

**Comment by rjwinks** [comment]
Thanks @benscobie! I saw the image update at 5:45 PST and the last time my rules ran were at 4:00 AM so I'll keep an eye on it.

**Comment by Zipties** [comment]
@benscobie 

> Please continue sharing your logs & the meta/manual flags when this happens, as there might be other scenarios where this is happening.

It usually happens at least twice a day. Would there be any value in giving you a week's worth of logs?

**Comment by Zipties** [comment]
@benscobie Here ya go, not noticing any different behavior [logs.zip](https://github.com/user-attachments/files/20394705/logs.zip)

**Comment by benscobie** [comment]
@Zipties Thank you for sharing. I think I have managed to track this down 🤞 I've just pushed an update to the Docker tag.

**Comment by mlamoure** [comment]
I just flipped to your pr tag and ran my rules.  One of the items that has been repeatedly been adding and removing was still removed, but at a closer look, something looks incorrect with the logic, unless I’m reading it wrong?  See below.  Shouldn’t id: 0 be true?



- plexId: 71593
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Last view date
          firstValue: 2024-08-21T01:50:13.000Z
          secondValueName: custom_days
          secondValue: 2024-11-24T10:27:37.938Z
          result: true
        - operator: OR
          action: equals
          firstValueName: Tautulli - Total views
          firstValue: 27
          secondValueName: number
          secondValue: 0
          result: false
    - id: 1
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue: []
          secondValueName: text
          secondValue: never_expire
          result: true
    - id: 2
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Date added
          firstValue: 2024-06-14T02:21:26.000Z
          secondValueName: custom_days
          secondValue: 2024-06-22T10:27:38.090Z
          result: true

**Comment by benscobie** [comment]
@mlamoure Hmm yes you're right. Was this a test media result or from the new (meta) link? Could you check that they both show the same result? Did you receive any errors in your logs when you ran this?

**Comment by mlamoure** [comment]
See below.  There's a key difference between when I run the Test Media versus the Meta (great feature by the way) in the Log:

**From Test Media via pr-1705:**

- plexId: 71593
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Last view date
          firstValue: 2024-08-21T01:50:13.000Z
          secondValueName: custom_days
          secondValue: 2024-11-24T11:44:50.824Z
          result: true
        - operator: OR
          action: equals
          firstValueName: Tautulli - Total views
          firstValue: 27
          secondValueName: number
          secondValue: 0
          result: false
    - id: 1
      result: true
      operator: AND                             <---  This
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue: []
          secondValueName: text
          secondValue: never_expire
          result: true
    - id: 2
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Date added
          firstValue: 2024-06-14T02:21:26.000Z
          secondValueName: custom_days
          secondValue: 2024-06-22T11:44:50.938Z
          result: true


**From Meta link in Log (pr-1705):**

plexId: 71593
result: false
sectionResults:
  - id: 0
    result: false
    ruleResults:
      - operator: OR
        action: before
        firstValueName: Tautulli - Last view date
        firstValue: 2024-08-21T01:50:13.000Z
        secondValueName: custom_days
        secondValue: 2024-11-24T03:17:40.489Z
        result: true
      - operator: OR
        action: equals
        firstValueName: Tautulli - Total views
        firstValue: 27
        secondValueName: number
        secondValue: 0
        result: false
    operator: OR
  - id: 1
    result: true
    operator: OR                  <----- This
    ruleResults:
      - operator: OR
        action: not_contains_partial
        firstValueName: Sonarr - [list] Tags (show)
        firstValue: []
        secondValueName: text
        secondValue: never_expire
        result: true
  - id: 2
    result: true
    operator: OR
    ruleResults:
      - operator: OR
        action: before
        firstValueName: Tautulli - Date added
        firstValue: 2024-06-14T02:21:26.000Z
        secondValueName: custom_days
        secondValue: 2024-06-22T03:17:43.214Z
        result: true

**Test Media from :main:**
- plexId: 71593
  result: true
  sectionResults:
    - id: 0
      result: true
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Last view date
          firstValue: 2024-08-21T01:50:13.000Z
          secondValueName: custom_days
          secondValue: 2024-11-24T11:54:51.465Z
          result: true
        - operator: OR
          action: equals
          firstValueName: Tautulli - Total views
          firstValue: 27
          secondValueName: number
          secondValue: 0
          result: false
    - id: 1
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: not_contains_partial
          firstValueName: Sonarr - [list] Tags (show)
          firstValue: []
          secondValueName: text
          secondValue: never_expire
          result: true
    - id: 2
      result: true
      operator: AND
      ruleResults:
        - operator: OR
          action: before
          firstValueName: Tautulli - Date added
          firstValue: 2024-06-14T02:21:26.000Z
          secondValueName: custom_days
          secondValue: 2024-06-22T11:54:51.608Z
          result: true


**Here's the rule:**
mediaType: SEASONS
rules:
  - "0":
      - firstValue: Tautulli.lastViewedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "180"
      - operator: OR
        firstValue: Tautulli.sw_amountOfViews
        action: EQUALS
        customValue:
          type: number
          value: 0
  - "1":
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: never_expire
  - "2":
      - operator: AND
        firstValue: Tautulli.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "335"

**Comment by Zipties** [comment]
@benscobie is there a way to confirm I'm pulling the latest build for pr-1705? My client says it is on the latest version of the image, but the digest doesn't match

```remote (amd64): sha256:e85c425352672f8b0a1cc186beef0057fa2b8f4215f99e5a0a1b4fc38af354ec
local  (amd64): sha256:6fdceb6c8b62b40aa82a2afac34cc133acdb5434c1d0b9715cf684a5df30daaf
root@dock-servarr:~# docker pull jorenn92/maintainerr:pr-1705
pr-1705: Pulling from jorenn92/maintainerr
Digest: sha256:6fdceb6c8b62b40aa82a2afac34cc133acdb5434c1d0b9715cf684a5df30daaf
Status: Image is up to date for jorenn92/maintainerr:pr-1705
docker.io/jorenn92/maintainerr:pr-1705
root@dock-servarr:~# 
```

develop-78a2111

**Comment by benscobie** [comment]
You can view the digest here:
https://github.com/jorenn92/Maintainerr/pkgs/container/maintainerr

Your local digest looks correct to me. Not sure why the remote is showing that one.

**Comment by rjwinks** [comment]
> [@rjwinks](https://github.com/rjwinks) I've just updated `jorenn92/maintainerr:pr-1705` to retry failed Plex API requests. Let me know how you get on with that change. I suggest manually running the rules after updating and verifying nothing crazy happens. Anybody else using this tag should also update.
> 
> I'm also working on adding more failure handling so that the rule group is skipped over if anything major fails so we don't end up removing everything. Though from all the logs I've seen so far I couldn't find a particular error message which signals that happening.



> You can view the digest here: https://github.com/jorenn92/Maintainerr/pkgs/container/maintainerr
> 
> Your local digest looks correct to me. Not sure why the remote is showing that one.
> 
> I'll update the tag with just released v2.15.0 later this evening.

Will v2.15.0 include the fix to retry failed Plex API requests? Or should I stay on pr-1705 build for now?

**Comment by benscobie** [comment]
@mlamoure Correct yes. v2.15 includes some fixes for specific scenarios like Plex API failures, but `pr-1705` still contains a lot more of them, like the potential fix for the mass add/removes, and the `(meta)` link (this will be in the next version). I will be picking out fixes from `pr-1705` to merge in once we've determined I haven't broken anything 😅

**Comment by benscobie** [comment]
@Zipties Sorry about that, should be fixed now.

**Comment by Zipties** [comment]
> [@Zipties](https://github.com/Zipties) Sorry about that, should be fixed now.

Yep it’s back online now. 

It's been churning through the add/removes again. The valid removals have meta, but the looped removals have no meta at all (as opposed to the manual label before)

[maintainerr-2025-05-26.log](https://github.com/user-attachments/files/20447104/maintainerr-2025-05-26.log)

**Comment by rjwinks** [comment]
fwiw, since I simplified my rules down to only use Sonarr/Radarr as sources I'm not getting the add/remove behavior anymore. I'm on 2.15.0 currently. The plex retry fix really has fixed my issue, but also simplifying my rules appears to have helped too

**Comment by Zipties** [comment]
I am also seeing that this rule has been behaving properly after the last update

```
mediaType: MOVIES
rules:
  - "0":
      - firstValue: Plex.seenBy
        action: CONTAINS
        lastValue: Overseerr.addUser
      - operator: AND
        firstValue: Overseerr.isRequested
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Overseerr.mediaAddedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "30"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
  - "1":
      - operator: OR
        firstValue: Overseerr.mediaAddedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "60"
      - operator: AND
        firstValue: Overseerr.isRequested
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
  - "2":
      - operator: OR
        firstValue: Plex.lastViewedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "365"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
  - "3":
      - operator: OR
        firstValue: Plex.viewCount
        action: EQUALS
        customValue:
          type: number
          value: 0
      - operator: AND
        firstValue: Plex.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "730"
      - operator: AND
        firstValue: Radarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
```

Where as this one is still churning

```
mediaType: SHOWS
rules:
  - "0":
      - firstValue: Sonarr.tags
        action: CONTAINS_PARTIAL
        customValue:
          type: text
          value: lists
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
      - operator: AND
        firstValue: Plex.lastViewedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "90"
  - "1":
      - operator: OR
        firstValue: Plex.sw_amountOfViews
        action: EQUALS
        customValue:
          type: number
          value: 0
      - operator: AND
        firstValue: Sonarr.tags
        action: CONTAINS
        customValue:
          type: text
          value: lists
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS_PARTIAL
        customValue:
          type: text
          value: dnd
```

btw, the new rule interface is much more readable
