### ISSUE TITLE
Smart collections not returning results

### ISSUE THREAD

**Issue by ztevo** [Maintainerr/Maintainerr#1762]
**Describe the bug**
The following rules do not appear to be working with smart collections:
- Plex - [list] Collections media is present in (titles) (incl. parents and smart collections)'
- Plex - [list] Collections media is present in (titles) (incl. smart collections)'

The "first value" is showing as []

I'm not sure if testing the above has also eventually caused the Smart Collection to bug out in Plex, as the collection I was testing against is now failing to show any content. (I can see it used to cause a database error - perhaps is the same thing?)

**To Reproduce**
1. Rate a show (e.g. GOT) 10 out of 10
2. Create smart list based on user rating (e.g. shows rated 8+ out of 10)
3. Call it "Top shows"
4. Use one of the above maintainer rules, with "partial contains" for the word "Top"

**Expected behavior**
GOT should appear as a result

**Screenshots**
```
  result: false
  sectionResults:
    - id: 0
      result: false
      ruleResults:
        - operator: OR
          action: contains_partial
          firstValueName: Plex - [list] Collections media is present in (titles) (incl.
            parents and smart collections)
          firstValue: []
          secondValueName: text
          secondValue: Top
          result: false
```

Also see result in Plex (this only happened after many times of testing, so may be unrelated):

![Image](https://github.com/user-attachments/assets/58cc1d9c-b3c8-47d8-8650-10d3375611d3)

**Device (please complete the following information):**
 - OS: Ubuntu / Linux
 - Version v2.14.0

**Additional context**
Issue was found following the need for https://github.com/jorenn92/Maintainerr/discussions/1760
