### ISSUE TITLE
[Bug] Something went wrong while updating settings

### ISSUE THREAD

**Issue by Azlaroc** [Maintainerr/Maintainerr#459]
**Describe the bug**
I have just got the docker up and running but I am unable to make any changes to settings

**To Reproduce**
```
version: "3"

services:
  maintainerr:
    restart: unless-stopped
    container_name: maintainerr
    image: jorenn92/maintainerr:latest
    hostname: maintainerr
    user: "1000:1001"

    environment:
      - TZ=Etc/UTC
      - PUID=1000
      - PGID=1001

    networks:
      - saltbox

    labels:
      com.github.saltbox.saltbox_managed: true 
      traefik.enable: true
      traefik.http.routers.maintainerr-http.entrypoints: web
      traefik.http.routers.maintainerr-http.middlewares: globalHeaders@file,authelia@docker,redirect-to-https,gzip
      traefik.http.routers.maintainerr-http.rule: Host(`maintainerr.domain.com`)
      traefik.http.routers.maintainerr-http.service: maintainerr
      traefik.http.routers.maintainerr.entrypoints: websecure
      traefik.http.routers.maintainerr.middlewares: globalHeaders@file,secureHeaders@file,authelia@docker
      traefik.http.routers.maintainerr.rule: Host(`maintainerr.domain.com`)
      traefik.http.routers.maintainerr.service: maintainerr
      traefik.http.routers.maintainerr.tls.certresolver: cfdns
      traefik.http.routers.maintainerr.tls.options: securetls@file
      traefik.http.services.maintainerr.loadbalancer.server.port: 80

    volumes:
      - /opt/maintainerr:/opt/data

networks:
  saltbox:
    external: true
```
I use that as my compose file. I bring it up and I am able to access the container webgui but I am unable to make any changes to settings

I see these errors:
[Nest] 100  - 09/09/2023, 2:48:15 PM   ERROR [TasksService] An error occurred while creating the CollectionHandler task
[Nest] 100  - 09/09/2023, 2:48:15 PM   DEBUG [TasksService] TypeError: Cannot read properties of undefined (reading 'onTick')
[Nest] 100  - 09/09/2023, 2:48:15 PM     LOG [CollectionWorkerService] Creation of job CollectionHandler failed. Retrying in 10s..
[Nest] 100  - 09/09/2023, 2:48:15 PM   ERROR [TasksService] An error occurred while creating the RuleHandler task
[Nest] 100  - 09/09/2023, 2:48:15 PM   DEBUG [TasksService] TypeError: Cannot read properties of undefined (reading 'onTick')
[Nest] 100  - 09/09/2023, 2:48:15 PM     LOG [RuleExecutorService] Creation of job RuleHandler failed. Retrying in 10s..
[Nest] 100  - 09/09/2023, 2:48:15 PM     LOG [NestApplication] Nest application successfully started +0ms
[Nest] 100  - 09/09/2023, 2:48:25 PM     LOG [TasksService] Task CollectionHandler created successfully
[Nest] 100  - 09/09/2023, 2:48:25 PM     LOG [TasksService] Task RuleHandler created successfully
[Nest] 100  - 09/09/2023, 2:48:45 PM    WARN [PlexApiService] Plex api communication failure.. Is the application running?
[Nest] 100  - 09/09/2023, 2:49:23 PM   ERROR [SettingsService] Something went wrong while updating settings

**Expected behavior**
I expect to be able to change settings and save

**Screenshots**

![image](https://github.com/jorenn92/Maintainerr/assets/30422117/71865a30-4c14-43f3-9f4e-6a09701a4968)
![image](https://github.com/jorenn92/Maintainerr/assets/30422117/113d5075-0021-4f8d-bb14-acfa0cb09414)

when i hit test it fails even though i know its right and i tested connectivity by pinging from a ash session
and when i hit save it says not all fields filled in which you can clearly see is not the case.

**Device (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version 1.4.2

**Additional context**
im using it on a saltbox configured system see https://github.com/saltyorg/Saltbox
