### ISSUE TITLE
[Bug] "Not all fields contain values" -> Not writing settings ?

### ISSUE THREAD

**Issue by Nesego** [Maintainerr/Maintainerr#552]
**Describe the bug**
Hi ! My issue seems similar to #459 except I can't even save settings for Plex at the very start. I tried adding to the compose a `1000:1000` user then removing it, did a chown to user `ubuntu`, paused every extension or iframe (using organizr) that could interfere and yet the same warning pops ! Can't figure out what's going on.
(Also, i laughed my ass off when reading you Readme, thanks 😜  : `Do your users constantly request media, and let it sit there afterward never to be touched again?`)

**To Reproduce**
Docker-compose is very light (no reverse proxy) :
```
maintainerr:
    image: jorenn92/maintainerr:latest
    container_name: maintainerr
    volumes:
      - /home/ubuntu/raspi-docker/maintainerr:/opt/data
    environment:
      - TZ=Europe/Paris
    ports:
      - 8154:80
    restart: unless-stopped
```

Log also shows Plex api communication failure : 
`WARN [PlexApiService] Plex api communication failure.. Is the application running?`

**Screenshots**
<img width="1026" alt="Capture d’écran 2023-10-26 à 12 51 26" src="https://github.com/jorenn92/Maintainerr/assets/40238259/7d63750a-8ba7-4675-98d1-53488fcc47dc">

**Device (please complete the following information):**
 - OS: Ubuntu Server 22
 - Docker install
