### ISSUE TITLE
TV shows are missing from Maintainerr when they are monitored but have no files

### ISSUE THREAD

**Issue by jberlyn** [Maintainerr/Maintainerr#892]
I currently have a rule setup that will automatically delete and unmonitor a season of a TV show if no one watches any episodes from that season for 90 days. This functionality works perfectly, no issues there.

However, in my circumstance, TV shows can get into a state where they are monitored in Sonarr, but none of the seasons are monitored and there are no files (because my previous rule has deleted and unmonitored the seasons).

If the show is a continuing show, it's not a problem because chances are my users will want to watch future seasons, so keeping it within Sonarr is useful because it'll grab those new episodes when they are available.

The issue I am running into is when shows have finished and have an Ended state in Sonarr. This leaves the show itself monitored in Sonarr, no seasons monitored, no episodes downloaded and no future episodes coming. In this case, I'd like to just have a rule that would delete the entire show from Sonarr since my users don't care about the show any more.

This seems pretty straight forward, however I noticed that shows that don't exist in Plex (which in my circumstance they won't any more, because the files are deleted) aren't interactable in the Maintainerr overview, or via Maintainerr rules/collections.

I have tried the following rules and none of them pickup the shows in that state:

```
mediaType: SHOWS
rules:
  - "0":
      - firstValue: Sonarr.ended
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Plex.sw_episodes
        action: EQUALS
        customValue:
          type: number
          value: 0
```

```
mediaType: SHOWS
rules:
  - "0":
      - firstValue: Sonarr.ended
        action: EQUALS
        customValue:
          type: boolean
          value: "true"
      - operator: AND
        firstValue: Sonarr.diskSizeEntireShow
        action: EQUALS
        customValue:
          type: number
          value: 0
```

Here are some screenshots the show's state in Sonarr.

![image](https://github.com/jorenn92/Maintainerr/assets/10014944/b48d7259-313a-4339-90c7-e22d5f740271)
![image](https://github.com/jorenn92/Maintainerr/assets/10014944/a0c60b52-e189-431b-9de8-2c7d6de1959c)

![image](https://github.com/jorenn92/Maintainerr/assets/10014944/cbffc2d6-6c6e-40d4-a23b-d0a91b0aabb6)
![image](https://github.com/jorenn92/Maintainerr/assets/10014944/034f3674-ea17-49ba-88ce-1319bf8280f3)

I am running Maintainerr on Docker, and my current version is v2.0.1.

**Comment by jorenn92** [comment]
Hey! I noticed your discussion in Discord a bit late, so I appreciate you bringing it up as an issue. That way, I don't have to read through the entire message history 😅.

Maintainerr is designed to fetch Plex's library data initially, so it doesn't recognize your monitored *arr items without data.
Changing this would be a significant alteration, potentially leading to unintended side effects.

Perhaps another solution could be adding a checkbox on the rule page. This checkbox would allow users to force-remove ended shows, even when the action is set to 'unmonitor'. What do you think?

**Comment by jberlyn** [comment]
> Perhaps another solution could be adding a checkbox on the rule page. This checkbox would allow users to force-remove ended shows, even when the action is set to 'unmonitor'. What do you think?

That could work. How would you envision the rule setup to be for my current scenario?

This is the rule set I have setup right now that tackles TV shows. The media type is set to `Seasons` and the Sonarr Action is set to `Unmonitor and delete season`.

```
mediaType: SEASONS
rules:
  - "0":
      - firstValue: Plex.addDate
        action: BEFORE
        customValue:
          type: custom_days
          value: "60"
      - operator: AND
        firstValue: Plex.sw_amountOfViews
        action: EQUALS
        customValue:
          type: number
          value: 0
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS
        customValue:
          type: text
          value: maintainerr-immunity
  - "1":
      - operator: OR
        firstValue: Plex.lastViewedAt
        action: BEFORE
        customValue:
          type: custom_days
          value: "60"
      - operator: AND
        firstValue: Sonarr.tags
        action: NOT_CONTAINS
        customValue:
          type: text
          value: maintainerr-immunity
```
